spring.application.name=medicas
spring.datasource.url=jdbc:oracle:thin:@fullstack1bd_high?TNS_ADMIN=/Wallet_Fullstack1BD 
spring.datasource.username=pelicula
spring.datasource.password=FullStack_2026_Java
# Driver actualizado
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=PELICULA

# Para ver qué está pasando realmente en la base de datos
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
